version: "3.1"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./pokeData:/data/db
    environment:
      - MONGO_INITDB_DATABASE=D2Randomizer
    ports:
      - 27017:27017
