name: Build CI

on:
  push:
    branches:
      - tlentz/**
      - dl/**

jobs:
  build:
    
    env:
      GOPATH: ${{ github.workspace }}
    
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [ 14.x ]
        go-version: [ 1.14.x ]

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        path: ./src/github.com/${{ github.repository }}
    - name: Build React
      working-directory: ./src/github.com/${{ github.repository }}
      run: bin/build_frontend
    - name: Build Backend
      working-directory: ./src/github.com/${{ github.repository }}
      run: go build gui/cmd/main.go
